### ISSUE TITLE
Enable branch protection, define CODEOWNERS

### ISSUE THREAD

**Issue by barabo** [anaconda-distribution/percy#10]
Since this is a public repo, we should protect the main branch and do whatever other repo changes are needed to 'productionalize' the dev process we use for it.  CODEOWNERS would not be a bad idea.

**Comment by schuylermartin45** [comment]
Minimal branch protections have been enabled on `main` AND our code checks have been enforced on PRs since last week.

I'm not aware of any company-wide best practices, but if there are any, I would love to know.
