### ISSUE TITLE
Target Python 3.11+

### ISSUE THREAD

**Issue by schuylermartin45** [anaconda-distribution/percy#45]
We should target a more modern version of Python as our minimum version. This gives us a few advantages:

- 3.11 has more type hinting features that will make it easier to work with static analysis tools.
- We're planning on using static analysis tools on all future projects
- We control the horizontal, we control the vertical too (i.e. this project is owned by us and there are few projects using it now; future projects should start targeting 3.11 by default)
- (In theory) this potentially shields us from some deprecation work until 3.11 becomes deprecated for at least 5 years

@cbouss as already raised the point that `abs-cli` targets Python 3.9 and that may become an issue.

**Comment by JeanChristopheMorinPerso** [comment]
Being too aggressive in what we support can be a problem. I generally see no problem is supporting older version like 3.9. Most newer typing features as made available through https://pypi.org/project/typing-extensions.

Supporting older versions is usually not much of a burden. I'm ok if we drop support for 3.7 and 3.8, but dropping 3.9 and 3.11 is quite aggresive.

**Comment by schuylermartin45** [comment]
After further discussion, we are not doing this. Closing.
