### ISSUE TITLE
Make parse tree an optional backend renderer of the Recipe class

### ISSUE THREAD

**Issue by cbouss** [anaconda-distribution/percy#48]
percy Recipe class can use multiple render backends.
At the moment, pyyaml, ruamel, and conda-build (to some extent) are supported. 

The parse tree implemented in #47 should be added as a possible render backend to the Recipe class.
render from https://github.com/anaconda-distribution/percy/blob/main/percy/render/_renderer.py#L158

This function takes a recipe in string representation, along with a selector dictionary which is applied to filter out information not relevant to the variant. It returns a python data structure.

**Comment by schuylermartin45** [comment]
I did this a while ago. The enum for the parse tree is `PERCY`. Closing.
